"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { modules } from "@/lib/modules";
import { repository } from "@/lib/repository";
import { auth, firebaseConfigured } from "@/lib/firebase";
import { ModuleId, RecordItem } from "@/types";
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut, User } from "firebase/auth";
import { Download, ExternalLink, LogOut, Menu, Plus, Search, Upload, X } from "lucide-react";

const labels:Record<string,string>={title:"Titolo",subtitle:"Descrizione",status:"Stato",machine:"Macchina",notes:"Note"};
export default function AppShell(){
 const [user,setUser]=useState<User|null>(null); const [authReady,setAuthReady]=useState(!firebaseConfigured);
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,u=>{setUser(u);setAuthReady(true)})},[]);
 if(!authReady)return <div className="loading">Connessione a Smart CNC Manager…</div>;
 if(firebaseConfigured&&!user)return <Login/>;
 return <Workspace user={user}/>;
}

function Login(){
 const [register,setRegister]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!auth)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));try{if(register)await createUserWithEmailAndPassword(auth,email,password);else await signInWithEmailAndPassword(auth,email,password)}catch(err){setError(err instanceof Error?err.message:"Accesso non riuscito")}finally{setBusy(false)}}
 return <main className="loginPage"><section className="loginCard"><div className="loginBrand"><span>SC</span><div><b>Smart CNC Manager</b><small>Professional Edition</small></div></div><h1>{register?"Crea il tuo account":"Accesso personale"}</h1><p>I dati e i file saranno protetti nel tuo spazio Firebase.</p><form onSubmit={submit}><label><span>Email</span><input name="email" type="email" required autoComplete="email"/></label><label><span>Password</span><input name="password" type="password" minLength={6} required autoComplete={register?"new-password":"current-password"}/></label>{error&&<div className="authError">{error}</div>}<button className="primary" disabled={busy}>{busy?"Attendere…":register?"Crea account":"Accedi"}</button></form><button className="textButton" onClick={()=>setRegister(!register)}>{register?"Hai già un account? Accedi":"Primo accesso? Crea account"}</button></section></main>
}

function Workspace({user}:{user:User|null}){
 const [active,setActive]=useState<ModuleId>("dashboard"); const [items,setItems]=useState<RecordItem[]>([]); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [mobile,setMobile]=useState(false); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [message,setMessage]=useState("");
 const uid=user?.uid;
 const refresh=async()=>{try{setItems(await repository.list(uid))}catch(e){setMessage(e instanceof Error?e.message:"Errore caricamento")}}; useEffect(()=>{refresh()},[uid]);
 const visible=useMemo(()=>items.filter(i=>(active==="dashboard"||i.module===active)&&Object.values(i).join(" ").toLowerCase().includes(query.toLowerCase())),[items,active,query]);
 const module=modules.find(m=>m.id===active)!;
 async function create(data:FormData){setBusy(true);setProgress(0);try{const now=new Date().toISOString();const id=crypto.randomUUID();let fileFields={};const file=data.get("file");if(file instanceof File&&file.size){if(firebaseConfigured&&uid)fileFields=await repository.upload(file,uid,active,id,setProgress);else fileFields={fileName:file.name,fileSize:file.size,fileType:file.type}}const item:RecordItem={id,module:active,title:String(data.get("title")||"Nuovo elemento"),subtitle:String(data.get("subtitle")||""),status:String(data.get("status")||"Attivo"),machine:String(data.get("machine")||""),notes:String(data.get("notes")||""),...fileFields,createdAt:now,updatedAt:now};await repository.save(item,uid);await refresh();setOpen(false);setMessage("Elemento salvato")}catch(e){setMessage(e instanceof Error?e.message:"Salvataggio non riuscito")}finally{setBusy(false);setProgress(0)}}
 async function backup(){const blob=new Blob([await repository.export(uid)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="smart-cnc-manager-backup.json";a.click();URL.revokeObjectURL(a.href)}
 async function remove(item:RecordItem){if(!confirm(`Eliminare ${item.title}?`))return;await repository.remove(item,uid);await refresh()}
 return <div className="app">
  <header><button className="mobileMenu" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="brand"><span>SC</span><div><b>Smart CNC Manager</b><small>Professional Edition</small></div></div><div className="globalSearch"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca in tutto il reparto…"/></div><div className={`cloud ${firebaseConfigured?"online":"demo"}`}><i/>{firebaseConfigured?"Firebase connesso":"Modalità demo"}</div>{user&&<button className="logout" onClick={()=>auth&&signOut(auth)} title="Esci"><LogOut size={17}/></button>}</header>
  <aside className={mobile?"show":""}><nav>{modules.map(m=><button key={m.id} className={active===m.id?"active":""} onClick={()=>{setActive(m.id);setMobile(false)}}><span>{m.icon}</span><div><b>{m.label}</b><small>{m.description}</small></div>{m.state!=="active"&&<em>{m.state==="config"?"Configura":"Standby"}</em>}</button>)}</nav><div className="asideFooter"><button onClick={backup}><Download size={16}/> Esporta backup</button><label><Upload size={16}/> Ripristina<input type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)f.text().then(async t=>{await repository.import(t,uid);await refresh();setMessage("Backup ripristinato")}).catch(()=>setMessage("Backup non valido"))}}/></label></div></aside>
  <main>{message&&<button className="notice" onClick={()=>setMessage("")}>{message} ×</button>}{active==="dashboard"?<Dashboard items={items} go={setActive}/>:<><div className="pageHead"><div><p>SMART CNC MANAGER</p><h1>{module.label}</h1><span>{module.description}</span></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/> Nuovo elemento</button></div><section className="records">{visible.length?visible.map(i=><article key={i.id}><button className="remove" onClick={()=>remove(i)}><X size={16}/></button><div className="recordIcon">{module.icon}</div><h3>{i.title}</h3><p>{i.subtitle||i.notes||"Nessuna descrizione"}</p><div className="tags">{i.machine&&<span>{i.machine}</span>}{i.status&&<span>{i.status}</span>}{i.fileName&&<span>{String(i.fileName)}</span>}</div>{Boolean(i.fileUrl)&&<a className="fileLink" href={String(i.fileUrl)} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Apri allegato</a>}</article>):<div className="empty"><strong>Nessun elemento trovato</strong><span>Aggiungi il primo contenuto a questo modulo.</span></div>}</section></>}</main>
  {open&&<div className="modal"><form action={create}><div className="modalHead"><div><small>NUOVO ELEMENTO</small><h2>{module.label}</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="formGrid">{["title","subtitle","status","machine"].map(k=><label key={k}><span>{labels[k]}</span><input name={k} required={k==="title"}/></label>)}<label className="full"><span>Note tecniche</span><textarea name="notes"/></label><label className="full upload"><Upload/><span>{firebaseConfigured?"Carica su Firebase Storage":"Allegato demo locale"}</span><input name="file" type="file"/></label>{busy&&progress>0&&<div className="full progress"><i style={{width:`${progress}%`}}/><span>Caricamento {progress}%</span></div>}</div><div className="modalActions"><button type="button" onClick={()=>setOpen(false)}>Annulla</button><button className="primary" disabled={busy}>{busy?"Salvataggio…":"Salva"}</button></div></form></div>}
 </div>
}
function Dashboard({items,go}:{items:RecordItem[];go:(id:ModuleId)=>void}){const count=(m:ModuleId)=>items.filter(x=>x.module===m).length;return <><div className="pageHead"><div><p>CONTROLLO REPARTO</p><h1>Dashboard operativa</h1><span>Tutte le informazioni tecniche in un unico sistema.</span></div></div><section className="kpis"><Kpi label="Macchine" value={count("machines")} icon="▦"/><Kpi label="Manuali" value={count("manuals")} icon="▤"/><Kpi label="Allarmi aperti" value={items.filter(x=>x.module==="alarms"&&x.status!=="Risolto").length} icon="⚠"/><Kpi label="Manutenzioni" value={count("maintenance")} icon="◆"/></section><section className="dashGrid"><div className="panel"><h2>Accesso rapido</h2><div className="quick">{modules.filter(x=>x.id!=="dashboard"&&x.state==="active").map(m=><button key={m.id} onClick={()=>go(m.id)}><span>{m.icon}</span><b>{m.label}</b><small>{count(m.id)} elementi</small></button>)}</div></div><div className="panel"><h2>Stato piattaforma</h2><div className="statusRow"><span>Interfaccia</span><b>Next.js + TypeScript</b></div><div className="statusRow"><span>Hosting</span><b>Vercel ready</b></div><div className="statusRow"><span>Dati</span><b>{firebaseConfigured?"Cloud Firestore":"Demo locale"}</b></div><div className="statusRow"><span>File</span><b>{firebaseConfigured?"Firebase Storage":"Metadati locali"}</b></div></div></section></>}
function Kpi({label,value,icon}:{label:string;value:number;icon:string}){return <div className="kpi"><span>{label}</span><div><strong>{value}</strong><i>{icon}</i></div></div>}
